kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: k8s-ai
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000
        hostPort: 30000
        protocol: TCP
      - containerPort: 30001
        hostPort: 30001
        protocol: TCP
      - containerPort: 30002
        hostPort: 30002
        protocol: TCP
    extraMounts:
      - hostPath: /Volumes/Other/rand/kind_vector_n8n/data
        containerPath: /data
        readOnly: false
