kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: k8s-ai-classic
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 31000
        hostPort: 31000
        protocol: TCP
      - containerPort: 31001
        hostPort: 31001
        protocol: TCP
      - containerPort: 31002
        hostPort: 31002
        protocol: TCP
    extraMounts:
      - hostPath: /Volumes/Other/rand/kind_vector_n8n/data
        containerPath: /data
        readOnly: false
