apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-classic-pvc
  namespace: k8s-classic-ai
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: qdrant-classic-pv
